### ISSUE TITLE
New Logo is shitty coloured (literally)

### ISSUE THREAD

**Issue by vagvaz** [kounabi/Jargon#1]
I feel the project has many pros, but in terms of graphics design is lacking especially in choosing colours.
I suggest porting the colours from shitty (literally do you the the brown?) to lively ping, red and orange with poua dots.
To reporduce this issue just clone this repository and open the log image.

**Comment by vagvaz** [comment]
Oh and I am proud to say that I am the 1st issue :)

**Comment by dchoroz** [comment]
I'm not an artist.....
